introduce -v flag to show version information
cloudfoundry/bosh-azure-storage-cli pull request #8
Opened 2023-07-14 14:46 UTC by fmoehler

2023-07-19 08:43 UTC, mvach approved these changes
Basically the same implementation as in the s3cli.
https://github.com/cloudfoundry/bosh-s3cli/blob/0cd5f9f23334e67dc1928e74f00bc8ac6708e879/main.go#L18

2023-07-19 08:46 UTC, mvach requested changes
Shouldn't we spend an integration test here?

2023-07-20 14:01 UTC, mvach approved these changes

2023-07-20 15:36 UTC, lnguyen approved these changes
LGTM

2023-07-20 15:36 UTC, merged